### ISSUE TITLE
Sky glitch [Bug Report]: 

### ISSUE THREAD

**Issue by CaseHardened** [Aurealis-Graphics/Lux-Shader#13]
### Describe the bug

sky is black. when I turn off round sun and moon the sky appears but has a weird half glitch to the sky.

I have tested the lates version and the dev build, same result.

### To reproduce

download the conquest reforged mod on the from the ATlauncher install both shaders.

### Expected behavior
not teal sky glitch

### Screenshots

![Screenshot (166)](https://github.com/TechDevOnGitHub/Lux-Shader/assets/108997964/eb1a7673-d7c0-4b2c-8550-ecc7025b2ffe)
![Screenshot (167)](https://github.com/TechDevOnGitHub/Lux-Shader/assets/108997964/b43b3371-d1e5-4d07-8fe1-1cf441c2bbd4)
![Screenshot (168)](https://github.com/TechDevOnGitHub/Lux-Shader/assets/108997964/d8e300b6-42cd-4ef8-a083-99e9b04f294d)
![Screenshot (169)](https://github.com/TechDevOnGitHub/Lux-Shader/assets/108997964/c1067b7a-381e-45cd-96c7-2cafd6357c2f)
![Screenshot (170)](https://github.com/TechDevOnGitHub/Lux-Shader/assets/108997964/b90ded6f-ea67-4342-b8c8-a4a8e05c061b)
![Screenshot (165)](https://github.com/TechDevOnGitHub/Lux-Shader/assets/108997964/2d985368-ec46-4c4b-9939-a47e6164bed4)

### Hardware specification

Nvidia 1070

driver 537.13

### Software specification

conquest reforged 1.19.2

Iris 1.5.2

### Additional context

added another photo to show black sky with terrain, while having the round sun and moon enabled

**Comment by CaseHardened** [comment]
I messed up on the reproduce tab... my bad.

One would need to simply download the conquest reforged and install the shader.

**Comment by TechDevOnGitHub** [comment]
I generally do not offer support for third party launchers, as they change the rendering pipeline in odd ways to fit their use cases.
I will close this issue for now. If you happen to still have this issue in the normal launcher don't hesitate the to reopen.
