### ISSUE TITLE
[Bug Report]: Enchantment texture doesn't render

### ISSUE THREAD

**Issue by Lord-Gravius** [Aurealis-Graphics/Lux-Shader#16]
### Describe the bug

When I have an enchanted object equipped in my hands, the texture or enchantment effect renders correctly without the shader. But if I activate the shader and start moving, the texture disappears or starts to glitch until I stop moving.

### To reproduce

1. Equip your hands with an enchanted object.
2. Move around

### Expected behavior

The enchantment effect of the object should remain the same whether it is still or moving.

### Screenshots

![2024-04-08_22 07 22](https://github.com/Aurealis-Graphics/Lux-Shader/assets/166442843/9a05ddad-824c-47ae-8352-6c60cce89984)
![2024-04-08_22 07 31](https://github.com/Aurealis-Graphics/Lux-Shader/assets/166442843/7d0db02e-961c-44ff-b1b0-c89e55fad776)
![2024-04-08_22 08 53](https://github.com/Aurealis-Graphics/Lux-Shader/assets/166442843/800bc9b5-1d41-4ab6-afbf-ffef95d7c17e)
![2024-04-08_22 07 57](https://github.com/Aurealis-Graphics/Lux-Shader/assets/166442843/70dc4626-8519-4d73-bf6c-51186cfa1c1e)

### Hardware specification

-Rtx 4060 Laptop

### Software specification

-Minecraft Java 1.20.4 -Optifine HD I7 Ultra - I have many mods, but I don't think I have any related to my problem.

**Comment by TechDevOnGitHub** [comment]
This should be fixed now. Screenshot taken while moving:

![2024-07-02_01 03 55](https://github.com/Aurealis-Graphics/Lux-Shader/assets/65711173/9d1d1b9d-f8dc-44d1-99a8-115f73f01a2b)

_Feel free to reopen the issue if it persists._
